version: "3"

services:
  next:
    restart: always
    build:
      context: .
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    env_file:
      - rpi.dev.env
  
  db:
    restart: always
    image: mariadb:10
    restart: always
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    env_file:
      - rpi.dev.env

  adminer:
    restart: always
    image: adminer
    restart: always
    ports:
      - 8080:8080
