version: "3"

services:
  next:
    restart: always
    build:
      context: .
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    env_file:
      - rpi.dev.env

  db:
    restart: always
    image: neo4j:4.3
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j-data:/data
    env_file:
      - rpi.dev.env
