version: "3.7"

services:
  web:
    build: .
    depends_on:
      - database
    restart: "always"
    ports:
      - "8101:80"
    volumes:
      - "./src/:/var/www/html/"
    networks:
      - backend

  database:
    image: "mariadb:${MARIADB_VERSION}"
    restart: "always"
    volumes:
      - "database-data:/var/lib/mysql/data"
      - "database-log:/var/lib/mysql/logs"
      - "./migrations:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    restart: "always"
    ports:
      - "8102:80"
    environment:
      PMA_HOST: "database"
      UPLOAD_LIMIT: 2G
    networks:
      - backend

volumes:
  database-data:
  database-log:

networks:
  backend:
